# Generated by Django 5.0.7 on 2024-12-19 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.building'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_type',
            field=models.CharField(blank=True, choices=[('all_tenants', 'All Tenants'), ('specific_tenants', 'Specific Tenants'), ('specific_building', 'Specific Building'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
